import 'dart:math';

class Motivation {
  static const List<String> thoughts = [
    'Small steps still move you forward.',
    'Consistency beats intensity when intensity cannot last.',
    'You do not need a perfect day. You need a next step.',
    'Your future self is built by what you repeat today.',
    'Progress is progress, even when it feels slow.',
    'Discipline makes ordinary days count.',
    'Start where you are. Use what you have. Keep going.',
    'One good choice can change the direction of a day.',
    'You are allowed to begin again.',
    'Do not compare your chapter one to someone else’s chapter twenty.',
    'A little better every day is a powerful strategy.',
    'The hardest step is often the first one.',
    'Keep promises to yourself.',
    'You can be tired and still take one small step.',
    'Your habits become the evidence of who you are becoming.',
    'Focus on showing up, not showing off.',
    'The goal is progress, not perfection.',
    'You cannot control every day, but you can control your next action.',
    'A missed day is a pause, not the end.',
    'Make today count.',
    'Your effort matters even when nobody sees it.',
    'Keep going. Your story is still being written.',
    'Choose the action your future self will appreciate.',
    'Confidence grows after you keep promises to yourself.',
    'Strong routines are built one repeat at a time.',
    'Do something today that makes tomorrow easier.',
    'You are closer than you think.',
    'Protect your momentum.',
    'Your only competition is yesterday’s version of you.',
    'Do not wait for motivation. Create momentum.',
    'One workout. One page. One task. One day.',
    'Consistency turns small actions into big results.',
    'You can restart without starting from zero.',
    'Keep your standards high and your excuses small.',
    'Your pace does not cancel your progress.',
    'Every completed checkbox is proof that you showed up.',
    'Make discipline feel like self-respect.',
    'The version of you that you want is built today.',
    'Keep the promise. Take the step.',
    'Hard days do not erase good habits.',
    'Progress can be quiet and still be real.',
    'Do not quit on a day that only needs rest.',
    'A strong life is made from simple repeated choices.',
    'Give yourself another chance.',
    'Your habits are votes for the person you want to become.',
    'Do less, but do it consistently.',
    'Make room for growth.',
    'The comeback can start today.',
    'Your next choice matters more than your last mistake.',
    'Stay patient with your progress.',
    'You are building something that takes time.',
    'Keep moving, even if the step is tiny.',
    'Your effort compounds.',
    'Be proud of every time you chose to continue.',
    'You do not need permission to start again.',
    'Today is another opportunity to keep your word.',
    'Make consistency your quiet superpower.',
    'Your routine is shaping your future.',
    'Take care of your body; it carries your dreams.',
    'A short walk is still movement.',
    'Water, sleep, movement, food, recovery — simple things matter.',
    'Train for strength, not punishment.',
    'Rest is part of progress.',
    'Fitness is a relationship with yourself, not a punishment.',
    'Move because your body deserves to feel alive.',
    'One healthy meal is a win.',
    'Do not chase perfect. Chase repeatable.',
    'Your body responds to what you practice.',
    'Strong habits create strong foundations.',
    'Read one more page.',
    'Learn something small today.',
    'Ten focused minutes can change a study session.',
    'Knowledge compounds too.',
    'Make your future easier by learning today.',
    'You do not need to know everything to begin.',
    'Ask questions. Stay curious.',
    'Practice turns information into ability.',
    'A little learning every day adds up.',
    'Your effort today becomes your skill tomorrow.',
    'You can do hard things one step at a time.',
    'Breathe. Reset. Continue.',
    'Be kind to yourself while still holding yourself accountable.',
    'You deserve the life you are willing to work toward.',
    'Protect your peace and your priorities.',
    'Do not let one difficult moment define the whole day.',
    'Progress includes rest, reflection and recovery.',
    'You are not behind. You are on your own timeline.',
    'Your best can look different every day.',
    'Take the pressure off perfection.',
    'Celebrate the small wins.',
    'The habit matters more than the mood.',
    'When in doubt, take the smallest useful action.',
    'You have survived difficult days before.',
    'Keep going until the habit feels normal.',
    'Make your next action obvious.',
    'Today does not need to be extraordinary to be meaningful.',
    'Never underestimate the power of showing up.',
    'Keep choosing yourself.',
    'Never give up on becoming better.',
    'You can start again right now.',
  ];

  static String forToday() {
    final now = DateTime.now();
    final seed = now.year * 10000 + now.month * 100 + now.day;
    return thoughts[Random(seed).nextInt(thoughts.length)];
  }
}
